//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataEntry", Namespace="http://schemas.datacontract.org/2004/07/SmartSocketsWebService")]
    [System.SerializableAttribute()]
    public partial class DataEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApplication1.ServiceReference1.Data DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeviceSignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EntryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsFormsApplication1.ServiceReference1.Data Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceSignature {
            get {
                return this.DeviceSignatureField;
            }
            set {
                if ((this.DeviceSignatureField.Equals(value) != true)) {
                    this.DeviceSignatureField = value;
                    this.RaisePropertyChanged("DeviceSignature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EntryType {
            get {
                return this.EntryTypeField;
            }
            set {
                if ((this.EntryTypeField.Equals(value) != true)) {
                    this.EntryTypeField = value;
                    this.RaisePropertyChanged("EntryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data", Namespace="http://schemas.datacontract.org/2004/07/SmartSocketsWebService")]
    [System.SerializableAttribute()]
    public partial class Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VoltageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Current {
            get {
                return this.CurrentField;
            }
            set {
                if ((this.CurrentField.Equals(value) != true)) {
                    this.CurrentField = value;
                    this.RaisePropertyChanged("Current");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Power {
            get {
                return this.PowerField;
            }
            set {
                if ((this.PowerField.Equals(value) != true)) {
                    this.PowerField = value;
                    this.RaisePropertyChanged("Power");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Voltage {
            get {
                return this.VoltageField;
            }
            set {
                if ((this.VoltageField.Equals(value) != true)) {
                    this.VoltageField = value;
                    this.RaisePropertyChanged("Voltage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Device", Namespace="http://schemas.datacontract.org/2004/07/SmartSocketsWebService")]
    [System.SerializableAttribute()]
    public partial class Device : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CommandsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeviceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeviceTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RoomIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Commands {
            get {
                return this.CommandsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandsField, value) != true)) {
                    this.CommandsField = value;
                    this.RaisePropertyChanged("Commands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((this.DeviceIDField.Equals(value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceName {
            get {
                return this.DeviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceNameField, value) != true)) {
                    this.DeviceNameField = value;
                    this.RaisePropertyChanged("DeviceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeviceTypeID {
            get {
                return this.DeviceTypeIDField;
            }
            set {
                if ((this.DeviceTypeIDField.Equals(value) != true)) {
                    this.DeviceTypeIDField = value;
                    this.RaisePropertyChanged("DeviceTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RoomID {
            get {
                return this.RoomIDField;
            }
            set {
                if ((this.RoomIDField.Equals(value) != true)) {
                    this.RoomIDField = value;
                    this.RaisePropertyChanged("RoomID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceType", Namespace="http://schemas.datacontract.org/2004/07/SmartSocketsWebService")]
    [System.SerializableAttribute()]
    public partial class DeviceType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeviceTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeviceTypeID {
            get {
                return this.DeviceTypeIDField;
            }
            set {
                if ((this.DeviceTypeIDField.Equals(value) != true)) {
                    this.DeviceTypeIDField = value;
                    this.RaisePropertyChanged("DeviceTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceTypeName {
            get {
                return this.DeviceTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceTypeNameField, value) != true)) {
                    this.DeviceTypeNameField = value;
                    this.RaisePropertyChanged("DeviceTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentLevel", Namespace="http://schemas.datacontract.org/2004/07/SmartSocketsWebService")]
    [System.SerializableAttribute()]
    public partial class PaymentLevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PaymentLevelIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PaymentLevelID {
            get {
                return this.PaymentLevelIDField;
            }
            set {
                if ((this.PaymentLevelIDField.Equals(value) != true)) {
                    this.PaymentLevelIDField = value;
                    this.RaisePropertyChanged("PaymentLevelID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Property", Namespace="http://schemas.datacontract.org/2004/07/SmartSocketsWebService")]
    [System.SerializableAttribute()]
    public partial class Property : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OwnerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PropertyIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OwnerID {
            get {
                return this.OwnerIDField;
            }
            set {
                if ((this.OwnerIDField.Equals(value) != true)) {
                    this.OwnerIDField = value;
                    this.RaisePropertyChanged("OwnerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PropertyID {
            get {
                return this.PropertyIDField;
            }
            set {
                if ((this.PropertyIDField.Equals(value) != true)) {
                    this.PropertyIDField = value;
                    this.RaisePropertyChanged("PropertyID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://schemas.datacontract.org/2004/07/SmartSocketsWebService")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PropertyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RoomIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PropertyID {
            get {
                return this.PropertyIDField;
            }
            set {
                if ((this.PropertyIDField.Equals(value) != true)) {
                    this.PropertyIDField = value;
                    this.RaisePropertyChanged("PropertyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RoomID {
            get {
                return this.RoomIDField;
            }
            set {
                if ((this.RoomIDField.Equals(value) != true)) {
                    this.RoomIDField = value;
                    this.RaisePropertyChanged("RoomID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomName {
            get {
                return this.RoomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNameField, value) != true)) {
                    this.RoomNameField = value;
                    this.RaisePropertyChanged("RoomName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Owner", Namespace="http://schemas.datacontract.org/2004/07/SmartSocketsWebService")]
    [System.SerializableAttribute()]
    public partial class Owner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OwnerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PaymentLevelIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OwnerID {
            get {
                return this.OwnerIDField;
            }
            set {
                if ((this.OwnerIDField.Equals(value) != true)) {
                    this.OwnerIDField = value;
                    this.RaisePropertyChanged("OwnerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PaymentLevelID {
            get {
                return this.PaymentLevelIDField;
            }
            set {
                if ((this.PaymentLevelIDField.Equals(value) != true)) {
                    this.PaymentLevelIDField = value;
                    this.RaisePropertyChanged("PaymentLevelID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISmartSocketsWebService")]
    public interface ISmartSocketsWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/AddDataEntry", ReplyAction="http://tempuri.org/ISmartSocketsWebService/AddDataEntryResponse")]
        bool AddDataEntry(WindowsFormsApplication1.ServiceReference1.DataEntry entry, string deviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetDataEntry", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetDataEntryResponse")]
        bool GetDataEntry(out WindowsFormsApplication1.ServiceReference1.DataEntry result, System.DateTime TimeStamp, string deviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetAllDataEntires", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetAllDataEntiresResponse")]
        bool GetAllDataEntires(out WindowsFormsApplication1.ServiceReference1.DataEntry[] result, string deviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/SetNewDevice", ReplyAction="http://tempuri.org/ISmartSocketsWebService/SetNewDeviceResponse")]
        bool SetNewDevice(out string ID, WindowsFormsApplication1.ServiceReference1.Device device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/UpdateDevice", ReplyAction="http://tempuri.org/ISmartSocketsWebService/UpdateDeviceResponse")]
        bool UpdateDevice(WindowsFormsApplication1.ServiceReference1.Device device);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/RemoveDevice", ReplyAction="http://tempuri.org/ISmartSocketsWebService/RemoveDeviceResponse")]
        bool RemoveDevice(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetDevice", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetDeviceResponse")]
        bool GetDevice(out WindowsFormsApplication1.ServiceReference1.Device result, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetAllDevices", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetAllDevicesResponse")]
        bool GetAllDevices(out WindowsFormsApplication1.ServiceReference1.Device[] result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetDeviceType", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetDeviceTypeResponse")]
        bool GetDeviceType(out WindowsFormsApplication1.ServiceReference1.DeviceType result, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetAllDeviceTypes", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetAllDeviceTypesResponse")]
        bool GetAllDeviceTypes(out WindowsFormsApplication1.ServiceReference1.DeviceType[] result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetPaymentLevel", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetPaymentLevelResponse")]
        bool GetPaymentLevel(out WindowsFormsApplication1.ServiceReference1.PaymentLevel result, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetAllPaymentLevels", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetAllPaymentLevelsResponse")]
        bool GetAllPaymentLevels(out WindowsFormsApplication1.ServiceReference1.PaymentLevel[] result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/SetNewProperty", ReplyAction="http://tempuri.org/ISmartSocketsWebService/SetNewPropertyResponse")]
        bool SetNewProperty(out string ID, WindowsFormsApplication1.ServiceReference1.Property property);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/UpdateProperty", ReplyAction="http://tempuri.org/ISmartSocketsWebService/UpdatePropertyResponse")]
        bool UpdateProperty(WindowsFormsApplication1.ServiceReference1.Property property);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/RemoveProperty", ReplyAction="http://tempuri.org/ISmartSocketsWebService/RemovePropertyResponse")]
        bool RemoveProperty(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetProperty", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetPropertyResponse")]
        bool GetProperty(out WindowsFormsApplication1.ServiceReference1.Property result, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetAllProperties", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetAllPropertiesResponse")]
        bool GetAllProperties(out WindowsFormsApplication1.ServiceReference1.Property[] result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/SetNewRoom", ReplyAction="http://tempuri.org/ISmartSocketsWebService/SetNewRoomResponse")]
        bool SetNewRoom(out string ID, WindowsFormsApplication1.ServiceReference1.Room room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/UpdateRoom", ReplyAction="http://tempuri.org/ISmartSocketsWebService/UpdateRoomResponse")]
        bool UpdateRoom(WindowsFormsApplication1.ServiceReference1.Room room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/RemoveRoom", ReplyAction="http://tempuri.org/ISmartSocketsWebService/RemoveRoomResponse")]
        bool RemoveRoom(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetRoom", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetRoomResponse")]
        bool GetRoom(out WindowsFormsApplication1.ServiceReference1.Room result, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetAllRooms", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetAllRoomsResponse")]
        bool GetAllRooms(out WindowsFormsApplication1.ServiceReference1.Room[] result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/SetNewOwner", ReplyAction="http://tempuri.org/ISmartSocketsWebService/SetNewOwnerResponse")]
        bool SetNewOwner(out string ID, WindowsFormsApplication1.ServiceReference1.Owner owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/UpdateOwner", ReplyAction="http://tempuri.org/ISmartSocketsWebService/UpdateOwnerResponse")]
        bool UpdateOwner(WindowsFormsApplication1.ServiceReference1.Owner owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/RemoveOwner", ReplyAction="http://tempuri.org/ISmartSocketsWebService/RemoveOwnerResponse")]
        bool RemoveOwner(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetOwner", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetOwnerResponse")]
        bool GetOwner(out WindowsFormsApplication1.ServiceReference1.Owner result, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmartSocketsWebService/GetAllOwners", ReplyAction="http://tempuri.org/ISmartSocketsWebService/GetAllOwnersResponse")]
        bool GetAllOwners(out WindowsFormsApplication1.ServiceReference1.Owner[] result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmartSocketsWebServiceChannel : WindowsFormsApplication1.ServiceReference1.ISmartSocketsWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmartSocketsWebServiceClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.ISmartSocketsWebService>, WindowsFormsApplication1.ServiceReference1.ISmartSocketsWebService {
        
        public SmartSocketsWebServiceClient() {
        }
        
        public SmartSocketsWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmartSocketsWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartSocketsWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmartSocketsWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddDataEntry(WindowsFormsApplication1.ServiceReference1.DataEntry entry, string deviceID) {
            return base.Channel.AddDataEntry(entry, deviceID);
        }
        
        public bool GetDataEntry(out WindowsFormsApplication1.ServiceReference1.DataEntry result, System.DateTime TimeStamp, string deviceID) {
            return base.Channel.GetDataEntry(out result, TimeStamp, deviceID);
        }
        
        public bool GetAllDataEntires(out WindowsFormsApplication1.ServiceReference1.DataEntry[] result, string deviceID) {
            return base.Channel.GetAllDataEntires(out result, deviceID);
        }
        
        public bool SetNewDevice(out string ID, WindowsFormsApplication1.ServiceReference1.Device device) {
            return base.Channel.SetNewDevice(out ID, device);
        }
        
        public bool UpdateDevice(WindowsFormsApplication1.ServiceReference1.Device device) {
            return base.Channel.UpdateDevice(device);
        }
        
        public bool RemoveDevice(int ID) {
            return base.Channel.RemoveDevice(ID);
        }
        
        public bool GetDevice(out WindowsFormsApplication1.ServiceReference1.Device result, int ID) {
            return base.Channel.GetDevice(out result, ID);
        }
        
        public bool GetAllDevices(out WindowsFormsApplication1.ServiceReference1.Device[] result) {
            return base.Channel.GetAllDevices(out result);
        }
        
        public bool GetDeviceType(out WindowsFormsApplication1.ServiceReference1.DeviceType result, int ID) {
            return base.Channel.GetDeviceType(out result, ID);
        }
        
        public bool GetAllDeviceTypes(out WindowsFormsApplication1.ServiceReference1.DeviceType[] result) {
            return base.Channel.GetAllDeviceTypes(out result);
        }
        
        public bool GetPaymentLevel(out WindowsFormsApplication1.ServiceReference1.PaymentLevel result, int ID) {
            return base.Channel.GetPaymentLevel(out result, ID);
        }
        
        public bool GetAllPaymentLevels(out WindowsFormsApplication1.ServiceReference1.PaymentLevel[] result) {
            return base.Channel.GetAllPaymentLevels(out result);
        }
        
        public bool SetNewProperty(out string ID, WindowsFormsApplication1.ServiceReference1.Property property) {
            return base.Channel.SetNewProperty(out ID, property);
        }
        
        public bool UpdateProperty(WindowsFormsApplication1.ServiceReference1.Property property) {
            return base.Channel.UpdateProperty(property);
        }
        
        public bool RemoveProperty(int ID) {
            return base.Channel.RemoveProperty(ID);
        }
        
        public bool GetProperty(out WindowsFormsApplication1.ServiceReference1.Property result, int ID) {
            return base.Channel.GetProperty(out result, ID);
        }
        
        public bool GetAllProperties(out WindowsFormsApplication1.ServiceReference1.Property[] result) {
            return base.Channel.GetAllProperties(out result);
        }
        
        public bool SetNewRoom(out string ID, WindowsFormsApplication1.ServiceReference1.Room room) {
            return base.Channel.SetNewRoom(out ID, room);
        }
        
        public bool UpdateRoom(WindowsFormsApplication1.ServiceReference1.Room room) {
            return base.Channel.UpdateRoom(room);
        }
        
        public bool RemoveRoom(int ID) {
            return base.Channel.RemoveRoom(ID);
        }
        
        public bool GetRoom(out WindowsFormsApplication1.ServiceReference1.Room result, int ID) {
            return base.Channel.GetRoom(out result, ID);
        }
        
        public bool GetAllRooms(out WindowsFormsApplication1.ServiceReference1.Room[] result) {
            return base.Channel.GetAllRooms(out result);
        }
        
        public bool SetNewOwner(out string ID, WindowsFormsApplication1.ServiceReference1.Owner owner) {
            return base.Channel.SetNewOwner(out ID, owner);
        }
        
        public bool UpdateOwner(WindowsFormsApplication1.ServiceReference1.Owner owner) {
            return base.Channel.UpdateOwner(owner);
        }
        
        public bool RemoveOwner(int ID) {
            return base.Channel.RemoveOwner(ID);
        }
        
        public bool GetOwner(out WindowsFormsApplication1.ServiceReference1.Owner result, int ID) {
            return base.Channel.GetOwner(out result, ID);
        }
        
        public bool GetAllOwners(out WindowsFormsApplication1.ServiceReference1.Owner[] result) {
            return base.Channel.GetAllOwners(out result);
        }
    }
}
